#! /usr/bin/python
# doc string
#import pickle
from threading import Thread
import urwid
import os
import pickle
import time
import logging
from IPython.kernel import KernelManager
from IPython.lib.kernel import find_connection_file
from Queue import Empty
from datetime import datetime
import optparse

palette = [
    ('body','black','light gray', 'standout'),
    ('reverse','light gray','black'),
    ('header','white','dark red', 'bold'),
    ('important','dark blue','light gray',('standout','underline')),
    ('editfc','white', 'dark blue', 'bold'),
    ('editbx','light gray', 'dark blue'),
    ('editcp','black','light gray', 'standout'),
    ('bright','dark gray','light gray', ('bold','standout')),
    ('buttn','black','dark cyan'),
    ('buttnf','white','dark blue','bold'),
    ]
# taken from http://nbviewer.ipython.org/gist/minrk/5672711
def collect_outputs(client, timeout=0.1):
    """flush the IOPub channel for outputs, and construct a dict of output data for each msg_id"""
    all_outputs = {}
    while True:
        try:
            msg = client.get_iopub_msg(timeout=timeout)
        except Empty:
            break
        parent_id = msg['parent_header'].get('msg_id', None)
        # no parent, ignore
        if not parent_id:
            continue
        if parent_id not in all_outputs:
            all_outputs[parent_id] = dict(stdout='', stderr='', display_data=[], pyout=[])
        outputs = all_outputs[parent_id]

        header = msg['header']
        msg_type = header['msg_type']
        content = msg['content']
        if msg_type == 'stream':
            outputs[content['name']] += content['data']
        elif msg_type in ('display_data', 'pyout'):
            outputs[msg_type].append(content)
    return all_outputs
######

class WatchWidget(urwid.Widget):

    _sizing = frozenset(['box'])
    signals = ['status']

    def __init__(self, connection_file='', async=True, timeout=0.5):
        self.status = {}
        self.timeout = timeout
        self.km = None
        self.cl = None
        self.kernel_dir = None
        self.connection_file = connection_file
        self.setup_kernel_manager(connection_file)
        # box_size and valid_size both hold size tuple. box_size is the last size the parent asked in the render, and valid_size is the size which 'self.content' was rendered with. Only if they match the widget will paint itself.
        self.box_size = None
        self.valid_size = None
        self.async = async
        if self.async:
            self.update_thread = Thread(target=self.update_loop)
            self.update_thread.setDaemon(True)
        self.content = []

    def set_status(self, key, value, unlogged_keys={'last_answer'}):
        if key in self.status and value==self.status[key]:
            return
        self.status[key] = value
        if key not in unlogged_keys:
            logging.debug('status of %s set to %s', key, value)
        self._emit('status', key, value)

    def setup_kernel_manager(self, connection_file=None):
        self.set_status('error', 'reconnecting...')
        if not connection_file:
            if self.kernel_dir:
                files = [os.path.join(self.kernel_dir,x) for x in os.listdir(self.kernel_dir)]
                stats = {}
                for f in files:
                    stats[f] = os.stat(f)
                max_mtime = max([x.st_mtime for x in stats.values()])
                options = [x for x,y in stats.items() if y.st_mtime==max_mtime]
                if len(options)==1:
                    connection_file = options[0]
            else:
                connection_file = '*'
        connection_file = find_connection_file(connection_file)
        self.set_status('connection_file', connection_file)
        logging.info('connection established to connection_file %s'%connection_file)
        if connection_file:
            self.kernel_dir = os.path.dirname(connection_file)
        self.km = KernelManager(connection_file=connection_file)
        self.km.load_connection_file()
        self.cl = self.km.client()
        self.cl.start_channels()
        self.exe('import pickle')
        self.exe('import urwid')
        self.exe('___top_widget = ___top_widget if "___top_widget" in globals() else urwid.Filler(urwid.Text("Hello, World!", align="center"), valign="middle")')

        self.exe('import IPWatch.watch_lib as wlib')

    def exe(self, s):
        return self.cl.execute(s, silent=True, store_history=False)
        #return self.cl.execute(s, silent=False, store_history=True)

    def refresh(self, timeout=0.5):
        content = []
        asked_size = self.box_size
        pending_request = self.exe('print pickle.dumps(list(___top_widget.render((%d,%d)).content()))'%(asked_size))
        outputs = collect_outputs(self.cl, timeout=timeout)
        got_outputs = bool(outputs)
        fine = False
        for msg_id, output in outputs.items():
            if msg_id==pending_request:
                try:
                    content_raw = output['stdout']
                    try:
                        content = pickle.loads(content_raw)
                        if not isinstance(content, list):
                            content = []
                            self.set_status('error','instructions must be a list')
                        else:
                            fine = True
                    except Exception:
                        content = []
                        self.set_status('error','no pickle')
                except IndexError:
                    raise

            pending_request = None
        if fine:
            self.set_status('error','')
        if content!=self.content:
            self._invalidate()
        if content:
            self.content = content
            self.valid_size = asked_size
        return got_outputs

    def update_loop(self):
        last_output = datetime.now()
        logging.debug('update loop started')
        while True:
            got_outputs = self.refresh(timeout=self.timeout)
            if got_outputs:
                last_output = datetime.now()
            self.set_status('last_answer', str(datetime.now()-last_output))
            time.sleep(1)

    def render(self, size, focus=False):
        self.box_size = size
        if self.async and not self.update_thread.is_alive():
            self.update_thread.start()
        logging.debug('rendering...')
        if self.content and self.valid_size == self.box_size:
            try:
                rows = []
                for row_elements in self.content:
                    row_content = ''.join([x[2] for x in row_elements])
                    rows.append(row_content)
                return urwid.TextCanvas(rows, maxcol=size[0])
            except Exception:
                logging.exception('cannot render. content is %s', str(self.content))
                self.set_status('error','cannot paint canvas')
                return urwid.TextCanvas(['e'*size[0]]*size[1], maxcol=size[0])
        else:
            return urwid.TextCanvas(['b'*size[0]]*size[1], maxcol=size[0])


class IPythonWatch(urwid.WidgetWrap):

    def selectable(self):
        return True

    def __init__(self, connection_file='', async=True, timeout=0.5):
        self.body = WatchWidget(connection_file=connection_file, async=async, timeout=timeout)
        divider = urwid.Filler(urwid.Divider(u'\u2500'))
        conn_file = os.path.basename(self.body.status['connection_file']) if self.body.status.get('connection_file') else 'no connection file'
        self.file_status = urwid.Text(conn_file, align='left')
        status_divider = urwid.Text('|', align='center')
        self.error_status = urwid.Text('error', align='center')
        self.last_update = urwid.Text('-', align='right')
        footer_columns = urwid.Filler(urwid.Columns([self.file_status, (1, status_divider), (20, self.error_status), (1, status_divider), self.last_update]))
        urwid.connect_signal(self.body, 'status', self.set_status)
        pile = urwid.Pile([self.body, (1, divider), (1, footer_columns)])
        urwid.WidgetWrap.__init__(self,urwid.LineBox(pile))

    def keypress(self, size, key):
        self.body.setup_kernel_manager()

    def set_status(self, a, key, value):
        if key=='error':
            self.error_status.set_text(value)
        if key=='connection_file':
            self.file_status.set_text(os.path.basename(value))
        if key=='last_answer':
            self.last_update.set_text(str(value))

def parse_args():
    parser = optparse.OptionParser(usage='usage: %prog [options]')
    parser.add_option('', '--connection-file', type='str', default='')
    parser.add_option('', '--log-file', type='str', default='')
    parser.add_option('-v', '--verbose', action='store_true')
    return parser.parse_args()

if __name__ == "__main__":
    options, args = parse_args()
    if options.log_file:
        logging.basicConfig(stream=open(options.log_file,'a'),
                format='%(asctime)s | %(levelname)-5s | IPWatch | %(message)s',
                datefmt='%Y/%m/%d %H:%M:%S',
                level=logging.DEBUG if options.verbose else logging.INFO)
    logging.info('Started')
    screen = urwid.raw_display.Screen()
    watch_widget = IPythonWatch(connection_file=options.connection_file, timeout=1)
    main_loop = urwid.MainLoop(watch_widget, palette, screen)
    def refresh(x,y):
        main_loop.set_alarm_in(1, refresh)
    main_loop.set_alarm_in(1, refresh)
    main_loop.run()
